
logging:
  level:
#    root: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

apps:
  private:
    stockma:
      codes:
        - 4689
        - 3402
        - 4902
        - 5020
        - 9434
        - 9508
        - 9984
      companies:
        4689: "Ｚホールディングス(株)"
        3402: "東レ(株)"
        4902: "コニカミノルタ(株)"
        5020: "ＥＮＥＯＳホールディングス(株)"
        9434: "ソフトバンク(株)"
        9508: "九州電力(株)"
        9984: "ソフトバンクグループ(株)"
      urls:
        4689: https://docs.google.com/spreadsheets/d/1JlhOrm1CNbmj5sG8zpJ3s_JNOwjVHsluZQm33Ott4Uo/edit?usp=sharing
        3402: https://docs.google.com/spreadsheets/d/1dw7O2P3STQGvD0W4SSHcNCjanW8QyXWiQynatPpb9iY/edit?usp=sharing
        4902: https://docs.google.com/spreadsheets/d/1oLnPNjUzxr_M8kpS1eLQzGpWN54DvYn0NaPdh5uazjU/edit?usp=sharing
        5020: https://docs.google.com/spreadsheets/d/13fjFRLSyrm2rFpmTTMcBtDzFTK6poPoog1CRfuBr3H4/edit?usp=sharing
        9434: https://docs.google.com/spreadsheets/d/1bffURdA5Meo6g0LzZ6S_WI5trr2ORL_U-pfu6SAYxy0/edit?usp=sharing
        9508: https://docs.google.com/spreadsheets/d/1vNVpON3ttYhjAtupwK3mn9-IrQImfzpkH3k77HHZPeE/edit?usp=sharing
        9984: https://docs.google.com/spreadsheets/d/1I8-Zjs6MTKv-jxIhWQAEnLMtlXhzvWFIVkWQAOjOd5k/edit?usp=sharing
    study:
      english:
        url: https://spreadsheets.google.com/feeds/list/1zHOtL6kBNJ9K_VB7hpC9Z2O0tAEkKs96e3iFHSDQxts/1/public/values?alt=json

security:
  bauth: # generate a hash at 'https://tool-taro.com/hash/' beforehand.
    n: 07f0eb95b88179306548d80af64eae1d8a2bd47ab1a936e8d5f308b0b14cd385dd93ae9485a4142bf937d574bfb7b3da58e41c8fcf865430d45eeeed61c5bb1f
    p: 0df8446cc922cd4a1824435876346895615586eec334cf3d89850cde34c9a0b8819a32bcc0477cd78b0b05b3c8b5dd3c78c9a07350e5c0385862268f754208b3
    algo: SHA-512
    digit: 128

